# Uncomment this line to define a global platform for your project
platform :ios, "7.0"

target "RedCard" do
    pod 'AFNetworking', '~> 2.2'
end

target "RedCardTests" do
    pod 'Specta',       '~> 0.2.1'
    pod 'Expecta',      '~> 0.2.4'
    pod 'OCMockito',    '~> 1.1'
end

